travis:
  secure:
    BINSTAR_TOKEN: nbWw31nT/gzlDbgEenS5QMrTvlpeH1UrW30SPO48BjgJ6rbQZQrDXL2hEp2ixY3p/qwKpJc7rlCJI8AEMNWO3YvVbKjC33cv43kld6DO4gESMwMXWpZSkVqifig2lzATiL4pgD/2w1S2TW7MN5QJGboAMf6+Ov0Ke/CXbBjNeUH26QCpcQw5t5ydBoetu31ZsOurZCo8GzyGv3dE+n4XrGhnFubR5+NS3Gshli2LncscYVVnnZRTVTlk0r8EOlqLA0Kg9HCoZoSS33m/gT4EBYtLEdsyRci9zO8aeNWAlYz30y3qVbmqjJP9yGpBHTnIukEHiT5fYnpClldDhR9tT7UvDCCZzBIzHHutLZ4oYpOrL3115buidW6n+GtMpdm3FAhV1FsVoLWkAIWt0ZlU4MgNuC0dBSb7NfwctGII9KGgL4Yo9tiFSLIbTyQqVvB2PUandq2jAh+U2kOUXhvgNnH847C1SHKHf70qNS3IfEHjpqG92ONzsAJD3E4CUUGZa+P1qzlrZySVhxh9llbJSFSHixoiSAORlTN0Px2Tqcv9uRYgIgeWTEA7KPvmgvQ/H+2/ldTtp+myNJAJUHzrEVAnfN9xZrUKWnm0knYmYG5dRmXbGH1fsoDLCvOgYxHLzr6iN+b27gFrOT4/j7A+lpPkfNRG3gFRHqxT4egcvaI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
