travis:
  secure:
    BINSTAR_TOKEN: vbbPb5ofgaMRree742wZgkImHdQTb2YXUyQmLQTukl84vIK6RDti1DIL6FGfKLW26M3kWG/AYK4C8vaDFiVuDa1w7CxPaX+2ForeJ6H/zGeNbpmVZxt+BGgNV11/Kmf8FDeGXsaTm+O/kO3DIQ1Mm199M2cjvnpHwKWCbiDuu2nO9B04yClYBFtBhJEMLIvSVC0HuX5arr9qLt5zkm2bnRxws4zNv1W2qASkmDOP2yhhY9YAJeUGhcm5BHkt5iWLccOpLAnIDT9iMq6nNqgckVVk0RDka+fMd2XWY7eo6woCXLRvxk+uOg+SvQ6eTwUWjm9fhz8hKLVBvcOT35CuNrzkm+jdKiC6D4AaOdjX1Fec1Mt54YPbP6ETeSRBw+NieQaNsQhNMuLlcYDrrv4Dnw61pyOOp5RcV6v4TE5oPCA1QSbBotpFj0XvMSMtGDSsO74I/nIaszqi3heFpCxXFEJVZiSmlZHfO9fxSWTua6zWtwsZv6lUOaHyq3zfT6m2awiAzOrl2lssP5zJLfljWYdjbU3MSnSDtOYLlyyql70VlaXSskNr3aRUkoQ55a2GW3OGpoYewUeWgLUPdenHrJy++cH/3FtX044KvDEipcBeC5fv4irzLKq3E7dQrUMA3I4FIVwzEFKy0aqQVJdoaAwE2CZe38V+NcBa+fi6DZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
